### ISSUE TITLE
Some questions about the FG contrastive loss

### ISSUE THREAD

**Issue by Eldo-rado** [HieuPhan33/MAVL#1]
👋 Hi, thanks for your contribution, it's really a good job! 

I have a question to confirm. In the FG contrastive loss, the distance between the image feature $f$ and its corresponding disease entity $c$'s visual aspect $a$ is pulled closer, while the distance between irrelevant $c$'s visual aspect $a$ is pulled further apart. 

However, as mentioned in the Introduction _"Second, new diseases can be described by elemental visual aspects of base diseases, e.g., Covid-19 has a texture of edema (grainy texture) and typically is located in a similar position as pneumothorax (lung edges)."_, **different disease entities $c$ sometimes share visual aspects $a$**. 

For example, if the current image category is COVID-19 rather than edema and pneumothorax, in the FG contrastive loss, all visual aspects possessed by COVID-19 (e.g., grainy texture, lung edges) are positive, while those of edema (e.g., the same 'grainy texture') and pneumothorax (e.g., the same 'lung edges') are all negative. Would this potentially lead to contradictions? 

I'm not sure about my thoughts and I hope you can help clarify. Thanks in advance! 😊

**Comment by HieuPhan33** [comment]
Hi @Eldo-rado,

That's an insightful question!

Due to the lack of aspect annotation per image, we agree that current implementation may have contradictory optimization in some cases. We note two observations.

First, it is not common to have contradictory cases where similar diseases with overlapped concepts have contradictory labels. Medical findings are only considered negative in RadGraph, when the doctor _explicitly_ mentioned "No {disease}" or "Absence of {disease}".  Thus, it is not common to have similar diseases (e.g., Edema and Pneumonia), which are contradictorily mentioned in the medical reports.

Second, even when contradictory optimization occurs in the FG contrastive loss, our contrastive inferencing remains robust against it. Unlike CLIP, when inferencing, we contrast the disease (e.g., Covid-19) with _normal finding_, not against other diseases. Thus, as long as the model yield a higher score of the _target disease than normal class_, the model still predicts the binary outcome accurately. This binary inferencing is robust during FG CL training, i.e., no contradictory optimization, where the aspects of normal findings and diseases are non-overlapping.

Again, I acknowledge your observation, which is very on point!

Indeed, in our extension, we would only consider concepts from a _normal class_ as negative, and only perform FG CL between positive disease's aspects with normal class's aspects. This will circumvent the contradictory optimization when similar but opposite diseases share the same aspects.

**Comment by Eldo-rado** [comment]
Thanks for your prompt reply, i got it!  Maybe we can also construct soft labels between visual aspects of different diseases. 
All in all, visual aspect is an interesting and meaningful idea! 😎
